name: Build and Push Docker Image

on:
  push:
    branches:
      - main # Trigger the workflow on pushes to the `main` branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write  # Required to push to GitHub Container Registry
      id-token: write  # Required for OIDC authentication

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Step 3: Build the Docker image
      - name: Build Docker Image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/quiz-app:latest .

      # Step 4: Push the Docker image to GitHub Container Registry
      - name: Push Docker Image
        run: |
          docker push ghcr.io/${{ github.repository }}/quiz-app:latest  